"""Synthetic phishing sample generation."""

from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Any

from app.utils.config import Settings, ensure_runtime_dirs


BRANDS = ["PayPal", "Microsoft 365", "Google Workspace", "Okta", "DocuSign", "Amazon"]
HOMOGLYPH_DOMAINS = ["paypaI", "micros0ft", "g00gle", "d0cusign", "arnazon", "0kta"]
TLD_CHOICES = [".com", ".support", ".click", ".work", ".top", ".zip"]
URGENCY_OPENERS = [
    "Your account has been suspended",
    "Immediate verification is required",
    "Security review detected unusual sign-in activity",
    "Payroll access will expire today",
    "Your mailbox storage has exceeded its limit",
]
CALLS_TO_ACTION = [
    "verify your credentials immediately",
    "reconfirm your enterprise password",
    "unlock your inbox and restore normal access",
    "review the pending invoice and validate your identity",
    "sign in to avoid permanent deactivation",
]
AI_TONES = [
    "This automated security notification was generated by our AI monitoring platform.",
    "Our adaptive risk engine flagged your account for anomalous behavior.",
    "The enterprise trust layer requires a fresh sign-in challenge.",
]


def generate_synthetic_text(count: int = 50, seed: int = 42) -> list[dict[str, Any]]:
    """Generate synthetic phishing text samples with varied attack themes."""

    rng = random.Random(seed)
    samples: list[dict[str, Any]] = []
    for index in range(count):
        brand = rng.choice(BRANDS)
        opener = rng.choice(URGENCY_OPENERS)
        call_to_action = rng.choice(CALLS_TO_ACTION)
        ai_tone = rng.choice(AI_TONES)
        sample_text = (
            f"{opener}. {ai_tone} To protect your {brand} profile, please {call_to_action} "
            "using the secure link below within 15 minutes."
        )
        samples.append(
            {
                "id": f"synthetic-text-{index}",
                "text": sample_text,
                "label": 1,
                "theme": brand.lower().replace(" ", "_"),
            }
        )
    return samples


def generate_synthetic_urls(count: int = 50, seed: int = 42) -> list[str]:
    """Generate phishing-style URLs containing homoglyphs and encoded parameters."""

    rng = random.Random(seed + 17)
    urls: list[str] = []
    for index in range(count):
        host = rng.choice(HOMOGLYPH_DOMAINS)
        tld = rng.choice(TLD_CHOICES)
        subdomains = [
            rng.choice(["auth", "secure", "login", "gateway", "verify"]),
            rng.choice(["portal", "cdn", "session", "account"]),
            rng.choice(["enterprise", "user", "mail"]),
        ]
        encoded_hint = rng.choice(
            [
                "ZXZlbnQ9dmVyaWZ5JnRva2VuPWFsZXJ0",
                "c2Vzc2lvbj1yZWZyZXNoJmF1dGg9dXJnZW50",
                "YWNjb3VudD1zeW5jJmxvY2FsZT1lbi1VUw==",
            ]
        )
        urls.append(
            f"http://{'.'.join(subdomains)}.{host}{tld}/update?continue={encoded_hint}&id={index}"
        )
    return urls


def create_synthetic_training_samples(count: int = 50, seed: int = 42) -> list[dict[str, Any]]:
    """Create a combined synthetic dataset pairing generated text and URLs."""

    texts = generate_synthetic_text(count=count, seed=seed)
    urls = generate_synthetic_urls(count=count, seed=seed)
    combined: list[dict[str, Any]] = []
    for item, url in zip(texts, urls, strict=False):
        combined.append({**item, "url": url, "combined_text": f"{item['text']} {url}"})
    return combined


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")


def save_generated_samples(
    *,
    settings: Settings | None = None,
    count: int = 50,
    seed: int = 42,
) -> dict[str, str]:
    """Persist generated phishing samples under the synthetic data directory."""

    effective = ensure_runtime_dirs(settings)
    output_dir = effective.synthetic_dir
    samples = create_synthetic_training_samples(count=count, seed=seed)
    text_path = output_dir / "synthetic_messages.jsonl"
    url_path = output_dir / "synthetic_urls.jsonl"
    combined_path = output_dir / "synthetic_training_samples.jsonl"
    _write_jsonl(text_path, [{"id": row["id"], "text": row["text"], "label": row["label"]} for row in samples])
    _write_jsonl(url_path, [{"id": row["id"], "url": row["url"], "label": row["label"]} for row in samples])
    _write_jsonl(combined_path, samples)
    return {
        "messages_path": str(text_path),
        "urls_path": str(url_path),
        "combined_path": str(combined_path),
    }


def load_synthetic_training_samples(settings: Settings | None = None, count: int = 50, seed: int = 42) -> list[tuple[str, int]]:
    """Return synthetic text samples for incremental retraining."""

    samples = create_synthetic_training_samples(count=count, seed=seed)
    return [(row["combined_text"], int(row["label"])) for row in samples]


if __name__ == "__main__":
    print(save_generated_samples())
